name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout des Repository-Codes
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installiere Node.js (Node 20 oder eine andere Version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Hier wird explizit Node.js 14 angegeben

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      # 3. Kopiere die gebauten Dateien auf die EC2-Instanz
      - name: Copy build files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}  
          username: ${{ secrets.USER_NAME }} 
          key: ${{ secrets.SSH_KEY }}  
          source: "./build/*"  
          target: "/home/${{ secrets.USER_NAME }}/build"  
          debug: true

      # 4. Führe Befehle auf der EC2-Instanz aus, um sicherzustellen, dass Docker installiert ist und den bestehenden Container stoppt.
      - name: Set up Docker and stop old container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.USER_NAME }}  
          key: ${{ secrets.SSH_KEY }}  
          script: |
            # Aktualisiere EC2-Instanz
            sudo yum update -y
            sudo yum upgrade -y

            # Installiere Docker, falls es nicht installiert ist
            if ! command -v docker &> /dev/null
            then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Stoppe und entferne den alten Docker-Container, falls er läuft
            if [ $(sudo docker ps -q --filter "name=calculatorapp") ]; then
              sudo docker stop calculatorapp
              sudo docker rm calculatorapp
            fi

      # 5. Docker Container starten
      - name: Start Docker Container on EC2 instance
        run: |
          ssh -i ~/.ssh/meinPrivateKey ec2-user@${{ secrets.EC2_IP }} << 'ENDSSH'
          docker run -d -p 80:3000 --name calculatorapp "${{ secrets.USER_NAME }}"/calculatorapp:latest
          ENDSSH
            

           